### ISSUE TITLE
Run BackSPIN from .loom file?

### ISSUE THREAD

**Issue by pierovatti** [linnarsson-lab/BackSPIN#13]
Hi, 

I'd like to run BackSPIN on my single-cell data (basically, I'm trying to follow the methods used by van Galen et al. (Cell, 2019)).
However, I'm having a hard time trying to create the appropriate cef file with ceftools and by looking at previous issues I noticed that you switched to .loom files. 
Is it possible to run BackSPIN from .loom files and, if so, how? 

thanks!

**Comment by pl-ki** [comment]
Hi,
This is not possible, and BackSPIN is not under active development.
Since .cef is a standard tab-delimited file with additional annotations in it,I would suggest you to export your data as a tab-delimited file and use your favourite Excel-like program to add the additional rows and columns as described in the format definition section of the ceftools github page.

best
