### ISSUE TITLE
Genes by cell subtypes

### ISSUE THREAD

**Issue by RaiaN** [linnarsson-lab/BackSPIN#2]
Hi. 
Could, you, please comment what is the file oligo.cef? I can't figure out how to get cell-subtype-specific genes from CEF file. Also could you please answer the following related questions? 

1) Why does oligo.cef contain only olygodendrocyte as column "Class" attribute (derive this from ceftools view)?

2) Is that possible that somewhere there are already lists of genes for each of cell subtype (according to Zeisel et al. Cell types in the mouse cortex and hippocampus revealed by single-cell RNA-seq Science 2015)? I really really need it....

Best regards,
Peter

**Comment by pl-ki** [comment]
Hi,
oligo.cef is intended as test file for the sorting algorithm of the BackSPIN software, and it only contains data from the oligodendrocytes, which is a reasonably sized test data set. If you need data for all cells investigated I suggest you download the companion data from http://linnarssonlab.org/cortex/
The aim of the Science paper is to delineate cell types, not to find marker genes, which in many cases seems difficult since rather combinations of genes discriminate cell types. I suggest you consult Fig 4 and Table S1 in the paper. The supplementary describes the methods by which these have been derived. You may also find the other items on http://linnarssonlab.org/cortex/ useful.
best,
Peter L

**Comment by RaiaN** [comment]
Thank you!
I was not trying to find marker genes, I only wanted to get list of genes for each cell-subtype which is probaby can be derived only by performing analysis from the beginning.
